apiVersion: v1
items:
- apiVersion: rbac.authorization.k8s.io/v1
  kind: Role
  metadata:
    annotations:
      meta.helm.sh/release-name: aws-load-balancer-controller
      meta.helm.sh/release-namespace: kube-system
    creationTimestamp: "2025-12-25T06:09:44Z"
    labels:
      app.kubernetes.io/instance: aws-load-balancer-controller
      app.kubernetes.io/managed-by: Helm
      app.kubernetes.io/name: aws-load-balancer-controller
      app.kubernetes.io/version: v2.17.0
      helm.sh/chart: aws-load-balancer-controller-1.17.0
    name: aws-load-balancer-controller-leader-election-role
    namespace: kube-system
    resourceVersion: "242307"
    uid: 543e995c-b016-4949-817f-7e8ca07350ec
  rules:
  - apiGroups:
    - ""
    resources:
    - configmaps
    verbs:
    - create
  - apiGroups:
    - ""
    resourceNames:
    - aws-load-balancer-controller-leader
    resources:
    - configmaps
    verbs:
    - get
    - patch
    - update
  - apiGroups:
    - coordination.k8s.io
    resources:
    - leases
    verbs:
    - create
  - apiGroups:
    - coordination.k8s.io
    resourceNames:
    - aws-load-balancer-controller-leader
    resources:
    - leases
    verbs:
    - get
    - update
    - patch
- apiVersion: rbac.authorization.k8s.io/v1
  kind: Role
  metadata:
    annotations:
      kubectl.kubernetes.io/last-applied-configuration: |
        {"apiVersion":"rbac.authorization.k8s.io/v1","kind":"Role","metadata":{"annotations":{},"name":"eks-vpc-resource-controller-role","namespace":"kube-system"},"rules":[{"apiGroups":["apps"],"resourceNames":["vpc-resource-controller"],"resources":["deployments"],"verbs":["get","list","watch"]},{"apiGroups":[""],"resourceNames":["amazon-vpc-cni"],"resources":["configmaps"],"verbs":["get","list","watch"]},{"apiGroups":[""],"resources":["configmaps"],"verbs":["create","list","watch"]},{"apiGroups":[""],"resourceNames":["cp-vpc-resource-controller"],"resources":["configmaps"],"verbs":["get","update","patch"]},{"apiGroups":[""],"resources":["events"],"verbs":["create"]},{"apiGroups":["coordination.k8s.io"],"resources":["leases"],"verbs":["create"]},{"apiGroups":["coordination.k8s.io"],"resourceNames":["cp-vpc-resource-controller"],"resources":["leases"],"verbs":["get","update"]}]}
    creationTimestamp: "2025-12-24T05:40:41Z"
    name: eks-vpc-resource-controller-role
    namespace: kube-system
    resourceVersion: "305"
    uid: 48b2c7f6-b7d5-4b76-9549-785cb3a7be49
  rules:
  - apiGroups:
    - apps
    resourceNames:
    - vpc-resource-controller
    resources:
    - deployments
    verbs:
    - get
    - list
    - watch
  - apiGroups:
    - ""
    resourceNames:
    - amazon-vpc-cni
    resources:
    - configmaps
    verbs:
    - get
    - list
    - watch
  - apiGroups:
    - ""
    resources:
    - configmaps
    verbs:
    - create
    - list
    - watch
  - apiGroups:
    - ""
    resourceNames:
    - cp-vpc-resource-controller
    resources:
    - configmaps
    verbs:
    - get
    - update
    - patch
  - apiGroups:
    - ""
    resources:
    - events
    verbs:
    - create
  - apiGroups:
    - coordination.k8s.io
    resources:
    - leases
    verbs:
    - create
  - apiGroups:
    - coordination.k8s.io
    resourceNames:
    - cp-vpc-resource-controller
    resources:
    - leases
    verbs:
    - get
    - update
- apiVersion: rbac.authorization.k8s.io/v1
  kind: Role
  metadata:
    annotations:
      kubectl.kubernetes.io/last-applied-configuration: |
        {"apiVersion":"rbac.authorization.k8s.io/v1","kind":"Role","metadata":{"annotations":{},"name":"eks:addon-manager","namespace":"kube-system"},"rules":[{"apiGroups":["policy"],"resourceNames":["ebs-csi-controller-pod-disruption-budget","ebs-csi-controller"],"resources":["poddisruptionbudgets"],"verbs":["create","delete","get","list","patch","update","watch"]},{"apiGroups":[""],"resourceNames":["coredns","kube-proxy","kube-proxy-config"],"resources":["configmaps"],"verbs":["create","delete","get","list","patch","update","watch"]},{"apiGroups":["apps"],"resourceNames":["aws-node","kube-proxy","ebs-csi-node","ebs-csi-node-windows"],"resources":["daemonsets"],"verbs":["create","delete","get","list","patch","update","watch"]},{"apiGroups":["apps"],"resourceNames":["coredns","ebs-csi-controller"],"resources":["deployments"],"verbs":["create","delete","get","list","patch","update","watch"]},{"apiGroups":[""],"resourceNames":["kube-dns"],"resources":["services"],"verbs":["create","delete","get","list","patch","update","watch"]},{"apiGroups":[""],"resourceNames":["coredns","aws-node","kube-proxy","ebs-csi-controller-sa","ebs-csi-node-sa"],"resources":["serviceaccounts"],"verbs":["create","delete","get","list","patch","update","watch"]}]}
    creationTimestamp: "2025-12-24T05:40:40Z"
    name: eks:addon-manager
    namespace: kube-system
    resourceVersion: "275"
    uid: 0ec4566a-d446-49e4-8d3c-6d5d01125e57
  rules:
  - apiGroups:
    - policy
    resourceNames:
    - ebs-csi-controller-pod-disruption-budget
    - ebs-csi-controller
    resources:
    - poddisruptionbudgets
    verbs:
    - create
    - delete
    - get
    - list
    - patch
    - update
    - watch
  - apiGroups:
    - ""
    resourceNames:
    - coredns
    - kube-proxy
    - kube-proxy-config
    resources:
    - configmaps
    verbs:
    - create
    - delete
    - get
    - list
    - patch
    - update
    - watch
  - apiGroups:
    - apps
    resourceNames:
    - aws-node
    - kube-proxy
    - ebs-csi-node
    - ebs-csi-node-windows
    resources:
    - daemonsets
    verbs:
    - create
    - delete
    - get
    - list
    - patch
    - update
    - watch
  - apiGroups:
    - apps
    resourceNames:
    - coredns
    - ebs-csi-controller
    resources:
    - deployments
    verbs:
    - create
    - delete
    - get
    - list
    - patch
    - update
    - watch
  - apiGroups:
    - ""
    resourceNames:
    - kube-dns
    resources:
    - services
    verbs:
    - create
    - delete
    - get
    - list
    - patch
    - update
    - watch
  - apiGroups:
    - ""
    resourceNames:
    - coredns
    - aws-node
    - kube-proxy
    - ebs-csi-controller-sa
    - ebs-csi-node-sa
    resources:
    - serviceaccounts
    verbs:
    - create
    - delete
    - get
    - list
    - patch
    - update
    - watch
- apiVersion: rbac.authorization.k8s.io/v1
  kind: Role
  metadata:
    creationTimestamp: "2025-12-24T05:40:38Z"
    name: eks:authenticator
    namespace: kube-system
    resourceVersion: "209"
    uid: 5af0f7f0-c0da-47eb-b697-4c819be137ce
  rules:
  - apiGroups:
    - ""
    resources:
    - events
    verbs:
    - create
    - update
    - patch
  - apiGroups:
    - ""
    resourceNames:
    - aws-auth
    resources:
    - configmaps
    verbs:
    - get
    - list
    - watch
- apiVersion: rbac.authorization.k8s.io/v1
  kind: Role
  metadata:
    creationTimestamp: "2025-12-24T05:40:38Z"
    name: eks:az-poller
    namespace: kube-system
    resourceVersion: "214"
    uid: 01c49db0-c76d-4f3d-a62e-43d8127c6a9d
  rules:
  - apiGroups:
    - coordination.k8s.io
    resourceNames:
    - kube-controller-manager
    - kube-scheduler
    - cloud-controller-manager
    - eks-certificates-controller
    - fargate-scheduler
    - cp-vpc-resource-controller
    - amazon-network-policy-controller-k8s
    - eks-coredns-autoscaler
    - kms-storage-migrator-lease
    - ebs-csi-eks-amazonaws-com
    - external-attacher-leader-ebs-csi-eks-amazonaws-com
    - external-resizer-ebs-csi-eks-amazonaws-com
    - external-snapshotter-leader-ebs-csi-eks-amazonaws-com
    - metric-agent-ebs-csi-eks-amazonaws-com
    - eks-load-balancer-controller-leader
    - ipam-controller
    - karpenter-controller
    resources:
    - leases
    verbs:
    - get
    - patch
- apiVersion: rbac.authorization.k8s.io/v1
  kind: Role
  metadata:
    creationTimestamp: "2025-12-24T05:40:38Z"
    name: eks:coredns-autoscaler
    namespace: kube-system
    resourceVersion: "220"
    uid: f206549a-6cef-4ecd-8747-8edcd4b3ba9a
  rules:
  - apiGroups:
    - coordination.k8s.io
    resources:
    - leases
    verbs:
    - create
  - apiGroups:
    - coordination.k8s.io
    resourceNames:
    - eks-coredns-autoscaler
    resources:
    - leases
    verbs:
    - get
    - update
    - patch
  - apiGroups:
    - apps
    resourceNames:
    - coredns
    resources:
    - deployments/scale
    verbs:
    - get
    - update
  - apiGroups:
    - ""
    resources:
    - events
    verbs:
    - create
    - patch
  - apiGroups:
    - ""
    resources:
    - pods
    verbs:
    - list
    - get
    - watch
  - apiGroups:
    - metrics.k8s.io
    resources:
    - pods
    verbs:
    - list
  - apiGroups:
    - ""
    resources:
    - pods/proxy
    verbs:
    - get
- apiVersion: rbac.authorization.k8s.io/v1
  kind: Role
  metadata:
    annotations:
      kubectl.kubernetes.io/last-applied-configuration: |
        {"apiVersion":"rbac.authorization.k8s.io/v1","kind":"Role","metadata":{"annotations":{},"name":"eks:fargate-manager","namespace":"kube-system"},"rules":[{"apiGroups":[""],"resourceNames":["aws-auth"],"resources":["configmaps"],"verbs":["get","update","patch","delete"]},{"apiGroups":[""],"resources":["configmaps"],"verbs":["create"]},{"apiGroups":[""],"resources":["events"],"verbs":["get","list"]}]}
    creationTimestamp: "2025-12-24T05:40:40Z"
    name: eks:fargate-manager
    namespace: kube-system
    resourceVersion: "268"
    uid: d817a73c-0111-45b8-b1c5-b714c04d7792
  rules:
  - apiGroups:
    - ""
    resourceNames:
    - aws-auth
    resources:
    - configmaps
    verbs:
    - get
    - update
    - patch
    - delete
  - apiGroups:
    - ""
    resources:
    - configmaps
    verbs:
    - create
  - apiGroups:
    - ""
    resources:
    - events
    verbs:
    - get
    - list
- apiVersion: rbac.authorization.k8s.io/v1
  kind: Role
  metadata:
    annotations:
      kubectl.kubernetes.io/last-applied-configuration: |
        {"apiVersion":"rbac.authorization.k8s.io/v1","kind":"Role","metadata":{"annotations":{},"labels":{"app.kubernetes.io/name":"amazon-network-policy-controller-k8s"},"name":"eks:network-policy-controller","namespace":"kube-system"},"rules":[{"apiGroups":[""],"resourceNames":["amazon-vpc-cni"],"resources":["configmaps"],"verbs":["get","list","watch"]},{"apiGroups":["coordination.k8s.io"],"resources":["leases"],"verbs":["create"]},{"apiGroups":["coordination.k8s.io"],"resourceNames":["amazon-network-policy-controller-k8s"],"resources":["leases"],"verbs":["get","update","patch"]},{"apiGroups":[""],"resources":["events"],"verbs":["create","patch"]}]}
    creationTimestamp: "2025-12-24T05:40:41Z"
    labels:
      app.kubernetes.io/name: amazon-network-policy-controller-k8s
    name: eks:network-policy-controller
    namespace: kube-system
    resourceVersion: "291"
    uid: 2d90f937-0965-498d-9dac-bb0f12f86ba3
  rules:
  - apiGroups:
    - ""
    resourceNames:
    - amazon-vpc-cni
    resources:
    - configmaps
    verbs:
    - get
    - list
    - watch
  - apiGroups:
    - coordination.k8s.io
    resources:
    - leases
    verbs:
    - create
  - apiGroups:
    - coordination.k8s.io
    resourceNames:
    - amazon-network-policy-controller-k8s
    resources:
    - leases
    verbs:
    - get
    - update
    - patch
  - apiGroups:
    - ""
    resources:
    - events
    verbs:
    - create
    - patch
- apiVersion: rbac.authorization.k8s.io/v1
  kind: Role
  metadata:
    annotations:
      kubectl.kubernetes.io/last-applied-configuration: |
        {"apiVersion":"rbac.authorization.k8s.io/v1","kind":"Role","metadata":{"annotations":{},"name":"eks:node-manager","namespace":"kube-system"},"rules":[{"apiGroups":[""],"resourceNames":["aws-auth"],"resources":["configmaps"],"verbs":["get","update","patch"]},{"apiGroups":[""],"resources":["configmaps"],"verbs":["create"]},{"apiGroups":[""],"resources":["events"],"verbs":["get","list"]}]}
    creationTimestamp: "2025-12-24T05:40:40Z"
    name: eks:node-manager
    namespace: kube-system
    resourceVersion: "259"
    uid: 639b9056-33b8-4acb-8f07-15e1bb34ef01
  rules:
  - apiGroups:
    - ""
    resourceNames:
    - aws-auth
    resources:
    - configmaps
    verbs:
    - get
    - update
    - patch
  - apiGroups:
    - ""
    resources:
    - configmaps
    verbs:
    - create
  - apiGroups:
    - ""
    resources:
    - events
    verbs:
    - get
    - list
- apiVersion: rbac.authorization.k8s.io/v1
  kind: Role
  metadata:
    creationTimestamp: "2025-12-24T05:40:39Z"
    name: eks:service-operations-configmaps
    namespace: kube-system
    resourceVersion: "236"
    uid: c069cac9-8d62-402a-856b-128d25154a5b
  rules:
  - apiGroups:
    - ""
    resourceNames:
    - coredns
    - cp-vpc-resource-controller
    - kube-proxy
    - kube-proxy-config
    resources:
    - configmaps
    verbs:
    - get
  - apiGroups:
    - ""
    resourceNames:
    - aws-auth
    resources:
    - configmaps
    verbs:
    - get
    - create
    - delete
    - patch
    - update
- apiVersion: rbac.authorization.k8s.io/v1
  kind: Role
  metadata:
    annotations:
      rbac.authorization.kubernetes.io/autoupdate: "true"
    creationTimestamp: "2025-12-24T05:40:37Z"
    labels:
      kubernetes.io/bootstrapping: rbac-defaults
    name: extension-apiserver-authentication-reader
    namespace: kube-system
    resourceVersion: "180"
    uid: 9ec5145f-15a4-40a6-85ba-f2da303a2db8
  rules:
  - apiGroups:
    - ""
    resourceNames:
    - extension-apiserver-authentication
    resources:
    - configmaps
    verbs:
    - get
    - list
    - watch
- apiVersion: rbac.authorization.k8s.io/v1
  kind: Role
  metadata:
    annotations:
      meta.helm.sh/release-name: karpenter
      meta.helm.sh/release-namespace: karpenter
    creationTimestamp: "2026-01-03T17:10:14Z"
    labels:
      app.kubernetes.io/instance: karpenter
      app.kubernetes.io/managed-by: Helm
      app.kubernetes.io/name: karpenter
      app.kubernetes.io/version: 1.8.3
      helm.sh/chart: karpenter-1.8.3
    name: karpenter-dns
    namespace: kube-system
    resourceVersion: "2896742"
    uid: 7b7c4159-3c3f-401a-a9dd-debbcdac7886
  rules:
  - apiGroups:
    - ""
    resourceNames:
    - kube-dns
    resources:
    - services
    verbs:
    - get
- apiVersion: rbac.authorization.k8s.io/v1
  kind: Role
  metadata:
    annotations:
      rbac.authorization.kubernetes.io/autoupdate: "true"
    creationTimestamp: "2025-12-24T05:40:37Z"
    labels:
      kubernetes.io/bootstrapping: rbac-defaults
    name: system::leader-locking-kube-controller-manager
    namespace: kube-system
    resourceVersion: "184"
    uid: 315a76d0-50b2-4c83-84f8-8bf23d800328
  rules:
  - apiGroups:
    - ""
    resources:
    - configmaps
    verbs:
    - watch
  - apiGroups:
    - ""
    resourceNames:
    - kube-controller-manager
    resources:
    - configmaps
    verbs:
    - get
    - update
  - apiGroups:
    - coordination.k8s.io
    resources:
    - leases
    verbs:
    - create
    - get
    - list
    - update
    - watch
  - apiGroups:
    - coordination.k8s.io
    resources:
    - leasecandidates
    verbs:
    - create
    - get
    - list
    - update
    - watch
- apiVersion: rbac.authorization.k8s.io/v1
  kind: Role
  metadata:
    annotations:
      rbac.authorization.kubernetes.io/autoupdate: "true"
    creationTimestamp: "2025-12-24T05:40:37Z"
    labels:
      kubernetes.io/bootstrapping: rbac-defaults
    name: system::leader-locking-kube-scheduler
    namespace: kube-system
    resourceVersion: "185"
    uid: 32f8f3cc-bf00-4465-951f-89a86d72740d
  rules:
  - apiGroups:
    - ""
    resources:
    - configmaps
    verbs:
    - watch
  - apiGroups:
    - ""
    resourceNames:
    - kube-scheduler
    resources:
    - configmaps
    verbs:
    - get
    - update
  - apiGroups:
    - coordination.k8s.io
    resources:
    - leases
    verbs:
    - create
    - get
    - list
    - update
    - watch
  - apiGroups:
    - coordination.k8s.io
    resources:
    - leasecandidates
    verbs:
    - create
    - get
    - list
    - update
    - watch
- apiVersion: rbac.authorization.k8s.io/v1
  kind: Role
  metadata:
    annotations:
      rbac.authorization.kubernetes.io/autoupdate: "true"
    creationTimestamp: "2025-12-24T05:40:37Z"
    labels:
      kubernetes.io/bootstrapping: rbac-defaults
    name: system:controller:bootstrap-signer
    namespace: kube-system
    resourceVersion: "181"
    uid: 0a46bd65-1332-411a-9c66-a4b6fac45836
  rules:
  - apiGroups:
    - ""
    resources:
    - secrets
    verbs:
    - get
    - list
    - watch
- apiVersion: rbac.authorization.k8s.io/v1
  kind: Role
  metadata:
    annotations:
      rbac.authorization.kubernetes.io/autoupdate: "true"
    creationTimestamp: "2025-12-24T05:40:37Z"
    labels:
      kubernetes.io/bootstrapping: rbac-defaults
    name: system:controller:cloud-provider
    namespace: kube-system
    resourceVersion: "182"
    uid: 9167ff8e-33b4-49de-98e7-07ea3a221dbb
  rules:
  - apiGroups:
    - ""
    resources:
    - configmaps
    verbs:
    - create
    - get
    - list
    - watch
- apiVersion: rbac.authorization.k8s.io/v1
  kind: Role
  metadata:
    annotations:
      rbac.authorization.kubernetes.io/autoupdate: "true"
    creationTimestamp: "2025-12-24T05:40:37Z"
    labels:
      kubernetes.io/bootstrapping: rbac-defaults
    name: system:controller:token-cleaner
    namespace: kube-system
    resourceVersion: "183"
    uid: 054d5c90-a846-4777-babb-4200a1ec2785
  rules:
  - apiGroups:
    - ""
    resources:
    - secrets
    verbs:
    - delete
    - get
    - list
    - watch
  - apiGroups:
    - ""
    - events.k8s.io
    resources:
    - events
    verbs:
    - create
    - patch
    - update
kind: List
metadata:
  resourceVersion: ""
