apiVersion: v1
items:
- apiVersion: v1
  kind: Service
  metadata:
    annotations:
      meta.helm.sh/release-name: karpenter
      meta.helm.sh/release-namespace: karpenter
    creationTimestamp: "2026-01-03T17:10:15Z"
    labels:
      app.kubernetes.io/instance: karpenter
      app.kubernetes.io/managed-by: Helm
      app.kubernetes.io/name: karpenter
      app.kubernetes.io/version: 1.8.3
      helm.sh/chart: karpenter-1.8.3
    name: karpenter
    namespace: karpenter
    resourceVersion: "2896749"
    uid: 8ebd4a5f-89bb-45f9-b0c1-267256133944
  spec:
    clusterIP: 10.100.214.29
    clusterIPs:
    - 10.100.214.29
    internalTrafficPolicy: Cluster
    ipFamilies:
    - IPv4
    ipFamilyPolicy: SingleStack
    ports:
    - name: http-metrics
      port: 8080
      protocol: TCP
      targetPort: http-metrics
    selector:
      app.kubernetes.io/instance: karpenter
      app.kubernetes.io/name: karpenter
    sessionAffinity: None
    type: ClusterIP
  status:
    loadBalancer: {}
kind: List
metadata:
  resourceVersion: ""
