apiVersion: v1
items:
- apiVersion: v1
  kind: ServiceAccount
  metadata:
    creationTimestamp: "2025-12-24T05:40:47Z"
    name: attachdetach-controller
    namespace: kube-system
    resourceVersion: "356"
    uid: 6ad7fa79-360b-47d7-9870-6b4cc351f764
- apiVersion: v1
  kind: ServiceAccount
  metadata:
    creationTimestamp: "2025-12-24T05:40:38Z"
    name: aws-cloud-provider
    namespace: kube-system
    resourceVersion: "202"
    uid: c403b3ef-2793-49ed-bd50-817d7cb06cce
- apiVersion: v1
  kind: ServiceAccount
  metadata:
    annotations:
      eks.amazonaws.com/role-arn: arn:aws:iam::859666865164:role/EKS-LOAD-BALANCER
    creationTimestamp: "2025-12-24T06:38:11Z"
    labels:
      app.kubernetes.io/managed-by: eksctl
    name: aws-load-balancer-controller
    namespace: kube-system
    resourceVersion: "9804"
    uid: 8ff3e5f8-5385-42c3-b03c-f8407f868e7a
- apiVersion: v1
  kind: ServiceAccount
  metadata:
    creationTimestamp: "2025-12-24T05:47:14Z"
    labels:
      app.kubernetes.io/instance: aws-vpc-cni
      app.kubernetes.io/managed-by: Helm
      app.kubernetes.io/name: aws-node
      app.kubernetes.io/version: v1.20.4
      helm.sh/chart: aws-vpc-cni-1.20.4
      k8s-app: aws-node
    name: aws-node
    namespace: kube-system
    resourceVersion: "1307"
    uid: 60f5f862-f091-4c18-bf51-2f02644311e0
- apiVersion: v1
  kind: ServiceAccount
  metadata:
    creationTimestamp: "2025-12-24T05:40:44Z"
    name: certificate-controller
    namespace: kube-system
    resourceVersion: "323"
    uid: e02e8563-3676-4c3c-92d0-e62e774245fb
- apiVersion: v1
  kind: ServiceAccount
  metadata:
    creationTimestamp: "2025-12-24T05:40:47Z"
    name: clusterrole-aggregation-controller
    namespace: kube-system
    resourceVersion: "350"
    uid: b0bdacf9-d985-4924-9066-085aa880266e
- apiVersion: v1
  kind: ServiceAccount
  metadata:
    creationTimestamp: "2025-12-24T05:47:17Z"
    labels:
      eks.amazonaws.com/component: coredns
      k8s-app: kube-dns
    name: coredns
    namespace: kube-system
    resourceVersion: "1327"
    uid: 61993075-445a-46be-b4a5-962a91d58a0a
- apiVersion: v1
  kind: ServiceAccount
  metadata:
    creationTimestamp: "2025-12-24T05:40:46Z"
    name: cronjob-controller
    namespace: kube-system
    resourceVersion: "346"
    uid: 5bfb71e9-12d4-4c0d-b58f-497c5b46312f
- apiVersion: v1
  kind: ServiceAccount
  metadata:
    creationTimestamp: "2025-12-24T05:40:46Z"
    name: daemon-set-controller
    namespace: kube-system
    resourceVersion: "345"
    uid: 14b9847a-97f5-4dc6-b72d-ce45a27f4ada
- apiVersion: v1
  kind: ServiceAccount
  metadata:
    creationTimestamp: "2025-12-24T05:40:48Z"
    name: default
    namespace: kube-system
    resourceVersion: "363"
    uid: 73f561aa-ac5c-4f9e-84f8-eb758f3b55d8
- apiVersion: v1
  kind: ServiceAccount
  metadata:
    creationTimestamp: "2025-12-24T05:40:44Z"
    name: deployment-controller
    namespace: kube-system
    resourceVersion: "329"
    uid: 109f68c9-1d21-4cd2-99f8-8f06df978ea9
- apiVersion: v1
  kind: ServiceAccount
  metadata:
    creationTimestamp: "2025-12-24T05:40:46Z"
    name: disruption-controller
    namespace: kube-system
    resourceVersion: "342"
    uid: e88270d4-ac61-4c24-ab48-2c475a162d1c
- apiVersion: v1
  kind: ServiceAccount
  metadata:
    creationTimestamp: "2025-12-24T05:40:46Z"
    name: endpoint-controller
    namespace: kube-system
    resourceVersion: "344"
    uid: a773af50-5dd7-408c-9eb7-a81674e76304
- apiVersion: v1
  kind: ServiceAccount
  metadata:
    creationTimestamp: "2025-12-24T05:40:44Z"
    name: endpointslice-controller
    namespace: kube-system
    resourceVersion: "320"
    uid: 407ef164-9cb0-4208-93ac-f16e6101f24d
- apiVersion: v1
  kind: ServiceAccount
  metadata:
    creationTimestamp: "2025-12-24T05:40:45Z"
    name: endpointslicemirroring-controller
    namespace: kube-system
    resourceVersion: "338"
    uid: d3da04c2-645b-4829-816e-f56bac7527d7
- apiVersion: v1
  kind: ServiceAccount
  metadata:
    creationTimestamp: "2025-12-24T05:40:48Z"
    name: ephemeral-volume-controller
    namespace: kube-system
    resourceVersion: "360"
    uid: c8e2759f-631d-49aa-8d57-5b5b0abf7cfd
- apiVersion: v1
  kind: ServiceAccount
  metadata:
    creationTimestamp: "2025-12-24T05:40:46Z"
    name: expand-controller
    namespace: kube-system
    resourceVersion: "349"
    uid: 611c51a5-25ad-48a0-8cec-fef7672962b3
- apiVersion: v1
  kind: ServiceAccount
  metadata:
    creationTimestamp: "2025-12-24T05:40:44Z"
    name: generic-garbage-collector
    namespace: kube-system
    resourceVersion: "327"
    uid: 7e70bb33-9928-4bcd-9a75-d735be7af569
- apiVersion: v1
  kind: ServiceAccount
  metadata:
    creationTimestamp: "2025-12-24T05:40:44Z"
    name: horizontal-pod-autoscaler
    namespace: kube-system
    resourceVersion: "331"
    uid: d7e70133-e9db-4100-890e-c4f4dfc88144
- apiVersion: v1
  kind: ServiceAccount
  metadata:
    creationTimestamp: "2025-12-24T05:40:44Z"
    name: job-controller
    namespace: kube-system
    resourceVersion: "324"
    uid: 653395ad-93f3-44a9-b981-3b723599b508
- apiVersion: v1
  kind: ServiceAccount
  metadata:
    creationTimestamp: "2025-12-24T05:47:15Z"
    labels:
      eks.amazonaws.com/component: kube-proxy
      k8s-app: kube-proxy
    name: kube-proxy
    namespace: kube-system
    resourceVersion: "1317"
    uid: f768cc70-17a1-4a75-b4db-18ea32801067
- apiVersion: v1
  kind: ServiceAccount
  metadata:
    creationTimestamp: "2025-12-24T05:40:45Z"
    name: legacy-service-account-token-cleaner
    namespace: kube-system
    resourceVersion: "336"
    uid: ff635f0d-73d7-4f25-bc70-9716af1876df
- apiVersion: v1
  kind: ServiceAccount
  metadata:
    creationTimestamp: "2025-12-24T05:49:23Z"
    labels:
      app.kubernetes.io/instance: metrics-server
      app.kubernetes.io/managed-by: EKS
      app.kubernetes.io/name: metrics-server
      app.kubernetes.io/version: 0.7.2
    name: metrics-server
    namespace: kube-system
    resourceVersion: "1677"
    uid: 3f55895f-d4fd-4d1f-9fe1-8bc919872337
- apiVersion: v1
  kind: ServiceAccount
  metadata:
    creationTimestamp: "2025-12-24T05:40:44Z"
    name: namespace-controller
    namespace: kube-system
    resourceVersion: "326"
    uid: fcb608fd-d99e-4355-a42b-9cfa93409048
- apiVersion: v1
  kind: ServiceAccount
  metadata:
    creationTimestamp: "2025-12-24T05:40:38Z"
    name: node-controller
    namespace: kube-system
    resourceVersion: "204"
    uid: 4cb640f9-d135-4372-9311-6eb5156e34bd
- apiVersion: v1
  kind: ServiceAccount
  metadata:
    creationTimestamp: "2025-12-24T05:40:47Z"
    name: persistent-volume-binder
    namespace: kube-system
    resourceVersion: "355"
    uid: 1365da6e-7bbb-4de6-82ea-cceb338602fc
- apiVersion: v1
  kind: ServiceAccount
  metadata:
    creationTimestamp: "2025-12-24T05:40:46Z"
    name: pod-garbage-collector
    namespace: kube-system
    resourceVersion: "341"
    uid: df98811d-f78e-4a2f-b8c1-a11d4877b471
- apiVersion: v1
  kind: ServiceAccount
  metadata:
    creationTimestamp: "2025-12-24T05:40:44Z"
    name: pv-protection-controller
    namespace: kube-system
    resourceVersion: "328"
    uid: 74c3de8e-fa76-4f5e-a330-b0a7fadde690
- apiVersion: v1
  kind: ServiceAccount
  metadata:
    creationTimestamp: "2025-12-24T05:40:48Z"
    name: pvc-protection-controller
    namespace: kube-system
    resourceVersion: "357"
    uid: 45ecfa62-1376-4762-bdd4-8a35d95d0e86
- apiVersion: v1
  kind: ServiceAccount
  metadata:
    creationTimestamp: "2025-12-24T05:40:44Z"
    name: replicaset-controller
    namespace: kube-system
    resourceVersion: "325"
    uid: 3384f0f9-1810-465c-9878-88c54f1a7303
- apiVersion: v1
  kind: ServiceAccount
  metadata:
    creationTimestamp: "2025-12-24T05:40:44Z"
    name: replication-controller
    namespace: kube-system
    resourceVersion: "321"
    uid: cf71fe75-26cc-4905-a580-915dc905813c
- apiVersion: v1
  kind: ServiceAccount
  metadata:
    creationTimestamp: "2025-12-24T05:40:47Z"
    name: resourcequota-controller
    namespace: kube-system
    resourceVersion: "351"
    uid: 3085b908-e168-46f1-af82-22a28279dbf8
- apiVersion: v1
  kind: ServiceAccount
  metadata:
    creationTimestamp: "2025-12-24T05:40:45Z"
    name: root-ca-cert-publisher
    namespace: kube-system
    resourceVersion: "339"
    uid: 54ea1195-b97e-47ba-9c30-8cb25b6aa88a
- apiVersion: v1
  kind: ServiceAccount
  metadata:
    creationTimestamp: "2025-12-24T05:40:47Z"
    name: service-account-controller
    namespace: kube-system
    resourceVersion: "354"
    uid: 03d24f9f-e7e6-42e0-8f8e-1fccab1b8a99
- apiVersion: v1
  kind: ServiceAccount
  metadata:
    creationTimestamp: "2025-12-24T05:40:38Z"
    name: service-controller
    namespace: kube-system
    resourceVersion: "205"
    uid: c1fe843f-f6b4-4091-820d-cd21a97ce0a2
- apiVersion: v1
  kind: ServiceAccount
  metadata:
    creationTimestamp: "2025-12-24T05:40:44Z"
    name: statefulset-controller
    namespace: kube-system
    resourceVersion: "322"
    uid: 02ba39da-d999-4436-bb7a-d9ad32f5f5aa
- apiVersion: v1
  kind: ServiceAccount
  metadata:
    creationTimestamp: "2025-12-24T05:40:38Z"
    name: tagging-controller
    namespace: kube-system
    resourceVersion: "203"
    uid: e02a1d47-4c2c-41b0-99d8-d977629f96e2
- apiVersion: v1
  kind: ServiceAccount
  metadata:
    creationTimestamp: "2025-12-24T05:40:45Z"
    name: ttl-after-finished-controller
    namespace: kube-system
    resourceVersion: "335"
    uid: 28fe165c-c54e-4d90-b5c3-3eba42fe4d69
- apiVersion: v1
  kind: ServiceAccount
  metadata:
    creationTimestamp: "2025-12-24T05:40:46Z"
    name: ttl-controller
    namespace: kube-system
    resourceVersion: "348"
    uid: 7615e4e2-6451-4adc-b827-e76417889655
- apiVersion: v1
  kind: ServiceAccount
  metadata:
    creationTimestamp: "2025-12-24T05:40:45Z"
    name: validatingadmissionpolicy-status-controller
    namespace: kube-system
    resourceVersion: "340"
    uid: e13085ef-b411-46aa-8781-82d419c3c8d1
- apiVersion: v1
  kind: ServiceAccount
  metadata:
    creationTimestamp: "2025-12-24T05:40:45Z"
    name: volumeattributesclass-protection-controller
    namespace: kube-system
    resourceVersion: "334"
    uid: 5c9172c5-f2ee-46bb-8a7b-fec7fc5a2d47
kind: List
metadata:
  resourceVersion: ""
