apiVersion: v1
items:
- apiVersion: v1
  kind: ServiceAccount
  metadata:
    creationTimestamp: "2025-12-25T07:19:44Z"
    name: default
    namespace: ns-ums
    resourceVersion: "256050"
    uid: 6d4de720-5e52-4fe8-8b3d-0efe6c03fd4d
kind: List
metadata:
  resourceVersion: ""
