apiVersion: v1
items:
- apiVersion: v1
  kind: ServiceAccount
  metadata:
    creationTimestamp: "2025-12-24T05:40:48Z"
    name: default
    namespace: kube-node-lease
    resourceVersion: "366"
    uid: 8888bc59-0c9b-4274-ad7b-a8c065c3221e
kind: List
metadata:
  resourceVersion: ""
