apiVersion: v1
items:
- apiVersion: v1
  data:
    password: LUVUU1NIaG1EWUtyVmprcg==
  kind: Secret
  metadata:
    creationTimestamp: "2026-01-03T13:21:38Z"
    name: argocd-initial-admin-secret
    namespace: argocd
    resourceVersion: "2851444"
    uid: 9cb37f71-2cd9-410d-ba69-5b79a77632a5
  type: Opaque
- apiVersion: v1
  kind: Secret
  metadata:
    annotations:
      kubectl.kubernetes.io/last-applied-configuration: |
        {"apiVersion":"v1","kind":"Secret","metadata":{"annotations":{},"labels":{"app.kubernetes.io/component":"notifications-controller","app.kubernetes.io/name":"argocd-notifications-controller","app.kubernetes.io/part-of":"argocd"},"name":"argocd-notifications-secret","namespace":"argocd"},"type":"Opaque"}
    creationTimestamp: "2026-01-03T07:53:33Z"
    labels:
      app.kubernetes.io/component: notifications-controller
      app.kubernetes.io/name: argocd-notifications-controller
      app.kubernetes.io/part-of: argocd
    name: argocd-notifications-secret
    namespace: argocd
    resourceVersion: "2786794"
    uid: 187a6f20-1f41-41f8-aa6e-854f3c1d7d7d
  type: Opaque
- apiVersion: v1
  data:
    auth: dTF4ZzZTV1hwTkE0UTkwbQ==
  kind: Secret
  metadata:
    creationTimestamp: "2026-01-03T13:21:35Z"
    name: argocd-redis
    namespace: argocd
    resourceVersion: "2851405"
    uid: c37d41da-4102-45d6-9e40-c0ae81017e5d
  type: Opaque
- apiVersion: v1
  data:
    admin.password: JDJhJDEwJG5UL2VXYUlEeGsxL0NwLlp0VEdNcHVEWjBOaFh4SEd2LmJHR2dhTkRwaFBOLmhvRDdkS1A2
    admin.passwordMtime: MjAyNi0wMS0wM1QxMzoyMTozOFo=
    server.secretkey: MlpSeElLOFN4dlowVmZNblZJQlNhUFduQTdQSVArd2RGY2k5RFJ6TXlDcz0=
    tls.crt: LS0tLS1CRUdJTiBDRVJUSUZJQ0FURS0tLS0tCk1JSURZakNDQWtxZ0F3SUJBZ0lRS1d2ZHJCd08ySEw5QmVPSE8zMWdOakFOQmdrcWhraUc5dzBCQVFzRkFEQVMKTVJBd0RnWURWUVFLRXdkQmNtZHZJRU5FTUI0WERUSTJNREV3TXpFek1qRXpPRm9YRFRJM01ERXdNekV6TWpFegpPRm93RWpFUU1BNEdBMVVFQ2hNSFFYSm5ieUJEUkRDQ0FTSXdEUVlKS29aSWh2Y05BUUVCQlFBRGdnRVBBRENDCkFRb0NnZ0VCQUxmbER2cUQzZ0Nib0Z3QUpNdFVoSXovQmQ1a0kzd1ZXby9CamwxcmZqamtUeHhzbGpvYWxPWnIKSVo2S0tWbGpRVWJ3NEIvcENTU0pjQlQyYVBqdmJnSm94RytIYVYxTWlMSTMxUVBCTHNJbzR4cVFIbXJtQjFvRQpzb1ZHVHNtQUFOcXpGOGRxNE43b2R6SDAwWXRIYjVKVy9GNEZPZ2dDcGxvY3o5Ni9ha2x1WkdSRnQ0OTkvNEUvCkMvK2F5UmRSYWFKU2drRkdqK21MQlEyaGx2YlluZERPQWcwMGc3TkhCUDdLNHZVSUo2ZFZRQ0sxV1pCQUlMYkEKOXdiRVoxemxKb01NWTdPVDVrS1hNMGgvR21jamJuRExJZEszUzNxamF6dGY5bHVDZ0NvYUpHSkZoblY0Z3BOeQp0L0RxQ0dPcUhnWm9TYm5leGVaNFI4dDZ6aXMxRzJrQ0F3RUFBYU9Cc3pDQnNEQU9CZ05WSFE4QkFmOEVCQU1DCkJhQXdFd1lEVlIwbEJBd3dDZ1lJS3dZQkJRVUhBd0V3REFZRFZSMFRBUUgvQkFJd0FEQjdCZ05WSFJFRWREQnkKZ2dsc2IyTmhiR2h2YzNTQ0RXRnlaMjlqWkMxelpYSjJaWEtDRkdGeVoyOWpaQzF6WlhKMlpYSXVZWEpuYjJOawpnaGhoY21kdlkyUXRjMlZ5ZG1WeUxtRnlaMjlqWkM1emRtT0NKbUZ5WjI5alpDMXpaWEoyWlhJdVlYSm5iMk5rCkxuTjJZeTVqYkhWemRHVnlMbXh2WTJGc01BMEdDU3FHU0liM0RRRUJDd1VBQTRJQkFRQ09jWWxKVUtINC95UGQKNy9NTzlyeTJob0djNEliejJJM3M3bG9HQ2hpNlc0K1NhbkVXL3RHa3NRa0c3Z3hlZ1VWVEl2TjJxbndUenJwNgozVXljc3FIWWNCdUpCc0lZeDEvVU0yUi9nZ2JDcGdPK0JRQ3lHNXFnUFRKM3FwdngwcU4ydDFNNTJSUG16WlhICjQ0VHp3ZHZFWjR2cWdwbUJEYytSVUZiOUZyY00rUmNCTm1tUExHQnU2RG4wdzRHZXZUNWdTQ3JzbU5EYzhWaGwKNVdSMXpFSENVc0NSb1NNOUJvZTNMSlFCSTJBY2FuYnJzWjRTVUN5bW83TkU4THdBWGY4MExkM2ljS0V4N0ZQKwpPVjZnQUhjSkJxaHpKYVVpZ0h0Y3Jna0huQUJJNC9rSzkyRC9oL0UzVGlkWFg0Z3hQUE14TS9ua0lSVDQ5V0haCkVoR3ZXcTVkCi0tLS0tRU5EIENFUlRJRklDQVRFLS0tLS0K
    tls.key: LS0tLS1CRUdJTiBSU0EgUFJJVkFURSBLRVktLS0tLQpNSUlFcEFJQkFBS0NBUUVBdCtVTytvUGVBSnVnWEFBa3kxU0VqUDhGM21RamZCVmFqOEdPWFd0K09PUlBIR3lXCk9ocVU1bXNobm9vcFdXTkJSdkRnSCtrSkpJbHdGUFpvK085dUFtakViNGRwWFV5SXNqZlZBOEV1d2lqakdwQWUKYXVZSFdnU3loVVpPeVlBQTJyTVh4MnJnM3VoM01mVFJpMGR2a2xiOFhnVTZDQUttV2h6UDNyOXFTVzVrWkVXMwpqMzMvZ1Q4TC81ckpGMUZwb2xLQ1FVYVA2WXNGRGFHVzl0aWQwTTRDRFRTRHMwY0Uvc3JpOVFnbnAxVkFJclZaCmtFQWd0c0QzQnNSblhPVW1nd3hqczVQbVFwY3pTSDhhWnlOdWNNc2gwcmRMZXFOck8xLzJXNEtBS2hva1lrV0cKZFhpQ2szSzM4T29JWTZvZUJtaEp1ZDdGNW5oSHkzck9LelViYVFJREFRQUJBb0lCQUEvdHhLWWcrWUFpZXRtMQpQbnFwVThEMXp4K1VHM25DVE1HaWdhOG9ZanJSMWVOdnFYU1hmRm5ZSWtXZUVKWllVVjF3ZkcxdkxWWlBuRmlJCmZvKy9oNDhvWFltT21Hc1hOOGorS3BLa2IyVXNqdjFzU2VJM0VpQnpRelpsb0duMlR6eWlZamNwRkJqaTJINUkKaDBVUjkwRmREUWVrMnNHNlh3ZnpzbkxJTUUvelhSYlRRSjdrSTFaaUc1cFBJYlNwOWhVdlo2OUZmcjFBUGEwYwplcjJaeVlDWW9pbmNIbDJFUmY0bWFpek9NUmJsT2Z0RjFaMGpva3VjLzlSekh1QnhETGFoQWlxd1Q0NGRVRDNyCjRjaXJad3FNbGZNMzN0ZzJvaHFjR2pOMkNZR0k3M3BibDZXZUJXbjFOdUkxN2dLaXdWUmVHcU93aitIYjJmdU8KdTU0WnJDMENnWUVBNUFDalpkVmlYdG9ncTFmU3RhRmdsSW5ZZmpTUzk4cnhLSkxHbzUwMzBIaEQvREhqSGlNNgo1RVowa2FhTFZ2N0d2U1k3ZEhibXVibGhrY3V3VDNFZS9jTlRzclJ5SGRWRzBOUkt4Z2I0aTBxcWFYWndkRkVPClNBYzQ5ZzZSdzl0M1N2eFplYmdUbk1ydFF6OWtlUXBISDFncFNtejBSRFhiT016YiswSDFIUDBDZ1lFQXpubmYKcHczSW1GZkdPZkdzSTJPT2QyYlBMNWZrNnZCZDlFWmJNeHpRaXdtQWZBM2hja3ZZSjJ1WlRmNU5HNlpHdng5QQo3cVk2M1NSWVZFUC9uY1pxUjZlQmpFU2pOWmpaWEEwS2pNbm81dXFwcDZaZDIva0E3OStOeGRHMFJqZ3VUQ1MrCld4WEdjSGRtRUpKcDZ0THJtcW0zaHlPNzdpTjhVSWpvMTJmZCtkMENnWUFzQjdPR1J0N29VbGRjdjJrQmlsaU0KVnRKb0ROOFUyeXdYR2NFaWQ0bi95RG5ZeWdtQ0dHdVhDY1FaSElCc0hHZGt2NjFib0ZxT0l5NmthU0Z6TmZVMgpMREpOb0dzcE43YWxQVm56UkFWYllOL24zZWQ1anUyakcwSDB3bnVEeHk0U1hRa3FhRkhoUlk3c0hhSFpmaEtlCkN2aHVWdndVOEJHVnRub0UyNGZxUVFLQmdRQ3hjbll1dUo3VHBtTzZ1cU1JeXUvT1YvSHBZaTRmWnpJbjFDdGUKMHYyNjhCQ1hETXJiRXFtU3YxdENkekhIZUhCR290S0lCeDZCblZHNEliUlY0UWJIekFKL0RTSUMxdmkrcm9xSgprcUR4aTIwQW91NzVOSmVFajJqbFFLTWcwZm1nQU5nRHFjUWdOY3ptb3g0WjdPa0V3NlR4cEZsSGdRRytxTnNLCi9MMzlsUUtCZ1FEVFEvQVU1YjgwUE1UMU80dm1xMnNyRmxCbFdwZVMrWVdOak1SOUdKSVd0ZWI3NHZkSHdkRG4KQlJ1aHBVTE4yWTZHQUFFOUhuZitIZWxVVklFV0NwY3BRUzZXU1l3ajVieGxPMXpTc3NnUmdXSjNxYlVHWTVvRApmQ3BBRWFoSTExZmhnU2J1QXF0UmtJQURJdW1kZVZPNGZ3a3ZjcW9teE1UellDazNjY3MzckE9PQotLS0tLUVORCBSU0EgUFJJVkFURSBLRVktLS0tLQo=
  kind: Secret
  metadata:
    annotations:
      kubectl.kubernetes.io/last-applied-configuration: |
        {"apiVersion":"v1","kind":"Secret","metadata":{"annotations":{},"labels":{"app.kubernetes.io/name":"argocd-secret","app.kubernetes.io/part-of":"argocd"},"name":"argocd-secret","namespace":"argocd"},"type":"Opaque"}
    creationTimestamp: "2026-01-03T07:53:33Z"
    labels:
      app.kubernetes.io/name: argocd-secret
      app.kubernetes.io/part-of: argocd
    name: argocd-secret
    namespace: argocd
    resourceVersion: "2851448"
    uid: 02eb2da3-4c6b-45e3-b142-0baa478c7a16
  type: Opaque
kind: List
metadata:
  resourceVersion: ""
